# Site settings
title: Integration Guides for Using Solace Messaging
baseurl: "/solace-integration-guides" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceLabs/solace-integration-guides

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-get-started: http://dev.solace.com/get-started/java-tutorials/
links-dev-portal: http://dev.solace.com
links-docs-jms: http://docs.solace.com/Solace-JMS-API/JMS-home.htm
links-docs-jms-api: http://docs.solace.com/API-Developer-Online-Ref-Documentation/jms/index.html
links-docs-features: http://docs.solace.com/Features/Features-Intro.htm



#----------------------------------------------------
# Generally don't modify items below this point
url: "solacelabs.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  guides:
    output: true
    permalink: /:path/
